### ISSUE TITLE
Fix titles for documents sent to kindle.

### ISSUE THREAD

**Issue by aeorxc** [redundans/feeder.mobi#1]
Hi Jesper,

Thank you so much for this tool, it is super useful!

One issue arising from Amazon's side is that titles for the documents are not showing correctly. This means all entries sent by feeder.mobi end up on the kindle with title 'lastest_book'. 

Would it be kindly possible to modify the code to extract the actual title and use that as the file name sent to kindle?

Thanks!

**Comment by redundans** [comment]
Just the comment that was needed to motivate me to tackle this problem.

**Comment by redundans** [comment]
@aeorxc What do you think. Can we close this issue? I rolled out a fix for this last week.

**Comment by aeorxc** [comment]
I see the documents being sent are now call: 'Your daily update'

Ideally it should be taking the title of the article and displaying that. The limitation is with the current approach is you end up with multiple documents on your kindle called 'Your daily update' without being able to discern what each represents.

**Comment by redundans** [comment]
> The limitation is with the current approach is you end up with multiple documents on your kindle called 'Your daily update' without being able to discern what each represents.

I agree. The limitation with the "title of the article" is that we often collect several articles in one and the same book. Especially for those with weekly subscriptions. Maybe it would be ok to print the date of when the book was created in the title/filename?

**Comment by aeorxc** [comment]
I understand. My preference would ideally be for each article to be sent as a separate kindle item. However I appreciate you are providing this on a voluntary basis so don't want to burden you with extra feature requests. 

For now will close this request, thanks for looking into it!

**Comment by redundans** [comment]
That would maybe be a good future feature. Please open another issue for that. And I will look into it. I have to calculate what it will be in cost for increased amount of transaction mail if we send all articles as different mails.
